FROM golang:latest AS build

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o client ./cmd/client/main.go

FROM scratch

WORKDIR /app

COPY --from=build /app/client /app

CMD ["./client"]
