name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-go@v4
        name: bacana
        with:
          go-version: "1.22"
      - name: Build
        run: docker build -t bacana
