name: Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  teste_unitario:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-go@v4
        name: abacaxi123
        with:
          go-version: "1.22"
      - name: Run testes
        run: go test ./...
